name: Render CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        working-directory: ./football-stats-predictions
        run: chmod +x gradlew

      - name: Build and Test
        working-directory: ./football-stats-predictions
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: ./gradlew build --no-daemon --parallel --console=plain --build-cache

  deploy:
    name: Deploy to Render
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/automatic-ci-cd'

    steps:
      - name: Trigger Deploy in Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}